---
experiments:
  metero_use: ['PM10', 'SO2', 'NO2', 'O3', 'CO', 'T2M_C', 'D2M_C', 'PRES_hPa',
               'APCP1h_mm', 'RH2M_pct', 'WSPD100', 'WDIR100', 'Month', 'Weekday', 'Hour']
  save_npy: True
  dataset_num: 1
  model: PM25_GNN
#  model: PM25_GNN_nosub
#  model: GC_LSTM
#  model: LSTM
#  model: GRU
#  model: nodesFC_GRU
#  model: MLP

train:
  batch_size: 32
  epochs: 50
  exp_repeat: 10
  hist_len: 24  # Use 24 hours of historical data
  pred_len: 48  # Predict 48 hours into the future
  weight_decay: 0.0005
  early_stop: 10
  lr: 0.0005

filepath:
  GPU-Server:
    knowair_fp: ./processed_data/processed_data.npy
    results_dir: ./results

data:
  metero_var:
    ['PM2.5', 'PM10', 'SO2', 'NO2', 'O3', 'CO', 'T2M_C', 'D2M_C', 'PRES_hPa',
     'APCP1h_mm', 'RH2M_pct', 'WSPD100', 'WDIR100', 'U100', 'V100', 'Month',
     'Weekday', 'Hour', 'T2M_C(01)', 'D2M_C(01)', 'PRES_hPa(01)', 'APCP1h_mm(01)',
     'RH2M_pct(01)', 'WSPD100(01)', 'WDIR100(01)', 'U100(01)', 'V100(01)', 'PM2.5(01)']
     # Note: This is just a sample - full list includes all 666 features
     # See processed_data/feature_mapping.txt for complete list

forecast:
  use_hours: 48  # Can be set to 48 or 72 depending on prediction length
  forecast_vars: ['T2M_C', 'D2M_C', 'PRES_hPa', 'APCP1h_mm', 'RH2M_pct',
                  'WSPD100', 'WDIR100', 'U100', 'V100']  # 9 forecast variables

dataset:
  data_start: [[2022, 1, 1, 0, 0], GMT]
  data_end: [[2024, 12, 31, 23, 0], GMT]

  1:
    train_start: [[2022, 1, 1], GMT]
    train_end: [[2023, 12, 31], GMT]
    val_start: [[2024, 1, 1], GMT]
    val_end: [[2024, 6, 30], GMT]
    test_start: [[2024, 7, 1], GMT]
    test_end: [[2024, 12, 31], GMT]

  2:
    train_start: [[2022, 1, 1], GMT]
    train_end: [[2023, 6, 30], GMT]
    val_start: [[2023, 7, 1], GMT]
    val_end: [[2023, 9, 30], GMT]
    test_start: [[2023, 10, 1], GMT]
    test_end: [[2023, 12, 31], GMT]

  3:
    train_start: [[2022, 1, 1], GMT]
    train_end: [[2022, 12, 31], GMT]
    val_start: [[2023, 1, 1], GMT]
    val_end: [[2023, 3, 31], GMT]
    test_start: [[2023, 4, 1], GMT]
    test_end: [[2023, 6, 30], GMT]
